
%Part 1
%%%%ECE2312--Lab0
%Objective: Start coding in Matlab for Discrete-time Signal and Systems
% Examples in this lab assignment is taken from
%Ingle, V.K. and Proakis, J.G., 2011. Digital signal processing using
%MATLAB. CL-Engineering.
%Echoes are delayed signals, and as such are generated using delay
% units. For example, the combination of the direct sound represented by
% discrete signal y[n] and a single echo appearing D samples later (which is
% related to delay in seconds) can be generated by the equation of the form
% (called a difference equation)
% x[n] = y[n] + αy[n − D], |α| < 1
%where x[n] is the resulting signal and α models attenuation of the direct
% sound. Difference equations are implemented in MATLAB using the
% filter function. The echo is delayed by
%D = 4196 samples, which amount to 0.5 sec of delay because Handel’s
%hallelujah chorus is a digital sound about 9 seconds long, sampled
%at 8192 sam/sec.
clear all
load handel; % the signal is in y and sampling freq in Fs
%sound(y,Fs); pause(10); % Play the original sound
alpha = 0.9; D = 4196; % Echo parameters
b = [1,zeros(1,D),alpha]; % Filter parameters
x = filter(b,1,y); % Generate sound plus its echo
%sound(x,Fs); % Play sound with echo

%Echo Removal: An echo removal system is given by the difference equation
% w[n] + αw[n − D] = x[n]
% where x[n] is the echo-corrupted sound signal and w[n] is the output
% sound signal, which has the echo (hopefully) removed. Note again that
% this system is very simple to implement in software or hardware.
w = filter(1,b,x);
% sound(w,Fs)
t = tiledlayout(1,2);
a1 = nexttile;
title('Impulse response h(n)')
xlabel('n')
ylabel('Response')
impz(b, 1, 0:4197)
a2 = nexttile;


h = -20:1:120;
unit = zeros(1, 141);
for n = 1:141
    if h(n) > 0
        unit(n) = 1;
    else
        unit(n) = 0;
    end
end
%impz(b, 1, -20:120);
unit = unit_step(h);
plot(a2,-20:120, unit)
xlabel('n')
ylabel('Response')
title('Step Response h(n)')

%end part 1

%part 2


































function u = unit_step(n)
    u = (n >= 0);
end

